# Generated by Django 4.2.11 on 2024-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity_grams', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_required', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.ManyToManyField(to='appMealplan.ingredient')),
            ],
        ),
    ]
