version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - ./bin/data/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!1QAZ2wsx
      - MYSQL_DATABASE=foodopia
    ports:
      - 3306:3306
    container_name: foodopiaDB

  foodopia:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 foodopia.wsgi:application
    volumes:
      - .:/foodopia
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_MYSQL_DATABASE=foodopia
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=!1QAZ2wsx
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
      - DJANGO_REDIS_URL=redis:6379
      - DJANGO_SETTINGS_MODULE=foodopia.settings
    container_name: foodopia

